### PR TITLE
Added Fuse Support

### PR DESCRIPTION
**Pull request by tay10r**
This pull request adds support for fuse by creating a separate executable, `bmfs-fuse`.

`bmfs-fuse` required a lot of functionality from the original program. To provide this functionality, a lot of the code from `bmfs.c` was moved into a common file, `libbmfs.c`.  The code in this file was then modified to support the requirements of the fuse layer.

In the process of adding this functionality, a lot of the original code was cleaned up a little. You'll notice most of the global variables have been removed (all except the `disk` variable).

I tested the `bmfs` and `bmfs-fuse` programs before creating this pull request. The `bmfs` program was testing successfully with the `BareMetal` repository. It properly created the `bmfs.image` file and a successful test run indicated no errors. I then mounted `bmfs.image`, containing the operating system, and mounted it. After mounting it, I created a file called `readme.txt` and added the contents `Hello, world!` (with two newlines). I then unmounted the BMFS image and added the `cat` program from BareMetal-OS. The `cat` program successfully printed the text in `readme.txt` and I considered the work done.

### CODE REVIEW

**Comment by IanSeyler** [comment]
Is there a prerequisite for the needed header fuse.h?

**Comment by tay10r** [comment]
You'll have to install the fuse library.

```
apt-get install libfuse-dev
```

**Comment by IanSeyler** [comment]
All good! I've adjusted the README.md and fixed a minor compiler warning.

Great work!

**Comment by tay10r** [comment]
@IanSeyler thanks!

**Pull request merged**
